# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebe764fa953b8a62b379da065b7c50561824185276118ddd84e124aa94774fe9e2fc1d698d00f8f4d4a3eb030dfc99525d31c50254ec5a9fa678ffca85a9d3b

test:
  secret_key_base: 6cc1e5817b0b1143cd0cc934b8d9c450ed85b30791555a72e97961325d14f5a0f486678efd86b5046baec0b8c3322c87f79eef7fa4087a46d4e9959a13c037cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
